### ISSUE TITLE
DigitalOcean catalog of server sizes smaller than proposed by Nanobox

### ISSUE THREAD

**Issue by bertux** [nanobox-io/digital-ocean-adapter#1]
Hello,
When I clicked on the Scale button in my DigitalOcean server shown in my Nanobox's Dashboard it presents me more server sizes than what I see when I try to create droplets in my DigitalOcean's dashboard with the same account. First I have thought it may depends on the region but I have checked with every region and it has the same difference.
Is it a bug or a feature ?
I have looked at https://docs.nanobox.io/providers/create/#requesting-the-catalog to see how the catalog should be requested
I have looked at https://github.com/nanobox-io/nanobox-adapter-digitalocean/blob/master/lib/autoload/catalog.rb to see how it is requested but I'm new to this so I have tried yet to debug it.
Would it be possible for a beginner in this project to try to debug by running this Ruby code alone?

**Comment by tylerflint** [comment]
Hi @bertux. We just pull the options from their api, so perhaps their api is out of sync? I'll have to check that out.

**Comment by bertux** [comment]
Merci @tylerflint for this confirmation, so it means there are not using in their dashboard the same client to call their API than the Nanobox dashboard. I would be deceived to learn they don't call their API from their dashboard :-(
I have found https://github.com/digitalocean/droplet_kit#size-resource and https://www.digitalocean.com/community/tags/api to explain how to run the official DigitalOcean API client for Ruby which is named DropletKit as seen also in catalog.rb because it's using it.
So if I manage to reproduce this bug of the Size resource API by using DropletKit then I will upstream this issue to their github repo.
I suppose you have much better to do than checking that out. I will try to progress on this because it interests me.

**Comment by jedgalbraith** [comment]
@bertux We also cache that catalog data in a couple places. In this adapter and in the dashboard. So that could cause discrepancies as well. I've just updated both. Can you compare again?

FYI. I have plans of a more automated way of staying in sync, but it's not in place yet.

**Comment by bertux** [comment]
Thank you I will retry this weekend to verify it’s corrected.

Le jeu. 5 oct. 2017 à 01:19, jedgalbraith <notifications@github.com> a
écrit :
